[package]
name = "rpc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bincode = "2.0.1"
futures.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["full"] }
